name: cGAN_4
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - cudatoolkit-dev
  - numpy=1.23.5
  - scipy
  - ninja
  - cupy
  - pip:
      # - cupy-cuda11x
      - matplotlib
      - h5py
      - tqdm
      - imageio
      - opencv-python
      - PyYAML
      - scikit-image
      - scikit-learn
      - sigpy