checkpoint_dir: "/disk/xray0/tl3/project-cGAN/outputs/model"
data_parallel: 1

sense:
  calib_width: 32
  device: 0
  crop: 0.70
  kernel_width: 6

data:
  num_coils: 8
  channels: 16
  path: "/disk/xray0/tl3/project-cGAN/datasets/fastMRI"
  num_of_top_slices: 8
  resolution: 384
# path: "/disk/xray0/tl3/project-cGAN/datasets/subsample_fastMRI"

optimizer:
  lr: 0.001
  beta_1: 0
  beta_2: 0.99

train:
  batch_size: 12
  n_epochs: 100
  P: 2
  adv_weight: 0.01
  l1_weight: 1
  num_iters_discriminator: 1
  gp_weight: 10
  drift_weight: 0.001
# n_epochs: 100 (original number of epochs)
# batch_size <= 14

validate:
  batch_size: 12
  mu_std: 0.01
  psnr_threshold: 0.25
  P: 8
  cfid_P: 8

test:
  batch_size: 12
  P: 32
  cfid_P: 8
